# Generated by Django 2.1.3 on 2018-11-18 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20181119_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='founder',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
