# Generated by Django 2.1.3 on 2018-11-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20181119_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='img',
            field=models.ImageField(blank=True, default='default/default_team.png', upload_to=''),
        ),
    ]
