# Generated by Django 2.1.3 on 2018-11-19 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_team_img'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='member',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='team',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
