# Generated by Django 2.1.3 on 2018-11-19 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_teamrecruitpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamRecruitPost',
        ),
    ]
