# Generated by Django 2.1.3 on 2018-11-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_delete_teamrecruitpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRecruitPost',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=50)),
                ('img_cover', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
