# Generated by Django 2.1.3 on 2018-11-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20181115_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birtdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='codename',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
