# Generated by Django 2.1.3 on 2018-11-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20181115_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cover_img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
