# Generated by Django 2.1.3 on 2018-11-15 13:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20181115_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='msg',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
