# Generated by Django 2.1.3 on 2018-11-15 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_post_msg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='game',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
    ]
