# Generated by Django 2.1.3 on 2018-11-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_auto_20181115_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rank',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cover_img',
            field=models.ImageField(blank=True, default='default/default_cover.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img',
            field=models.ImageField(blank=True, default='default/default_profile.png', upload_to=''),
        ),
    ]
