# Generated by Django 2.1.3 on 2018-11-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0014_auto_20181117_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='msg',
            field=models.CharField(default='a', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mail',
            name='topic',
            field=models.CharField(default='b', max_length=50),
            preserve_default=False,
        ),
    ]
